import { StyleSheet } from 'react-native';

const AppStyles = StyleSheet.create({
  
  container: {
    padding: 20,
    backgroundColor: '#f0f4f7',
    marginBottom: 15,
  },
  containerfind: {
    padding: 20,
    backgroundColor: '#f0f4f7',
    //marginBottom: 5,
  },
  heading: {
    fontSize: 35,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    color: '#333',
  },
  header: {
    fontSize: 35,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    color: '#333',
  },
  label: {
    fontSize: 20,
    fontWeight: 'bold',
    marginVertical: 8,
    //color: '#555',
    color: '#000', 
  },
  input: {
    borderWidth: 3,
    borderColor: '#ddd',
    borderRadius: 15,
    padding: 10,
    fontSize: 20,
    backgroundColor: '#fff',
    marginBottom: 15,
    color: '#000', 
  },
  picker: {
    borderWidth: 3,
    borderColor: '#ddd',
    borderRadius: 15,
    paddingHorizontal: 10,
    marginBottom: 15,
    backgroundColor: '#fff',
    fontSize: 30,
    color: '#000', 
  },
  pickerContainer: {
    borderWidth: 3,
    borderColor: '#ddd',
    borderRadius: 15,
    paddingHorizontal: 10,
    marginBottom: 15,
    backgroundColor: '#fff',
    fontSize: 20,
    color: '#000', 
  },
  button: {
    backgroundColor: '#1E90FF',
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  probutton: {
    marginBottom: 40,
  },
  nextButton: {
    backgroundColor: '#4CAF50',
  },
  logoutButton: {
    backgroundColor: 'red',
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  message: {
    textAlign: 'center',
    marginTop: 15,
    fontSize: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2c3e50',
    textAlign: 'center',
    marginVertical: 10,
    color: '#000', 
  },
  text: {
    fontSize: 16,
    color: '#34495e',
    textAlign: 'center',
    marginVertical: 5,
    lineHeight: 22,
  },
  // New styles for LoginComponent
  loginBackground: {
    resizeMode: 'cover',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    height: '100%',
  },
  loginContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    paddingTop: '10%',
    paddingBottom: '10%',
    minHeight: '100%',
  },
  loginTitle: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 10,
  },
  loginSubtitle: {
    fontSize: 20,
    color: '#555',
    textAlign: 'center',
    marginBottom: 20,
  },
  loginInput: {
    height: 50,
    borderColor: '#ddd',
    borderWidth: 3,
    borderRadius: 8,
    paddingHorizontal: 15,
    fontSize: 20,
    marginBottom: 15,
    backgroundColor: '#f9f9f9',
    width: '60%',
    textAlign: 'center',
    justifyContent: 'center',
    color: '#000', 
  },
  loginButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 10,
    borderRadius: 15,
    alignItems: 'center',
    marginTop: 20,
    padding: 10,
  },
  loginButtonText: {
    color: '#fff',
    fontSize: 25,
    fontWeight: 'bold',
  },
  loginLogo: {
    width: 100,
    height: 100,
    marginBottom: 20,
  },
  // New styles for CustomButton
  customButton: {
    marginHorizontal: 10,
    backgroundColor: '#e0e0e0',
    borderColor: 'blue',
    borderWidth: 1,
    borderRadius: 5,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  customButtonText: {
    color: 'black',
    fontSize: 18,
  },

   // New styles for PropertyHouseComponent
  radioGroup: {
    flexDirection: 'row',
    alignItems: 'left',
  },
  radioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 20,
  },
  radioCircle: {
    height: 20,
    width: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#007bff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  selectedCircle: {
    backgroundColor: '#007bff',
  },
  radioText: {
    fontSize: 16,
    //color: '#000', 
  },
  tenantContainer: {
    marginBottom: 16,
    padding: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
  },
  documentButton: {
    backgroundColor: '#007BFF',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
    alignItems: 'center',
    marginBottom: 10,
  },
  photoButton: {
    backgroundColor: '#28A745',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
    alignItems: 'center',
    marginBottom: 10,
  },
  photoButtonText: {
    color: '#fff',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  photoText: {
    color: 'black',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  photoPreview: {
    width: 100,
    height: 100,
    resizeMode: 'cover',
    borderRadius: 5,
    marginTop: 5,
  },
    // New styles for TestComponent
    headerCenter: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 16,
      color: '#333',
      textAlign: 'center',
      color: '#000', 
    },
    photoContainer: {
      marginBottom: 20,
      backgroundColor: '#fff',
      padding: 10,
      borderRadius: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
      alignItems: 'center',
    },
    photoText: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 8,
      color: '#555',
      textAlign: 'center',
      color: '#000', 
    },
    captureButton: {
      backgroundColor: '#007bff',
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 5,
      marginBottom: 8,
    },
    tenantContainer: {
      marginBottom: 20,
      backgroundColor: '#fff',
      padding: 10,
      borderRadius: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
    documentButton: {
      backgroundColor: '#007BFF',
      padding: 10,
      borderRadius: 5,
      marginTop: 10,
      alignSelf: 'center',
    },
    photoButtonText: {
      color: '#FFFFFF',
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 16,
    },
    photoText: {
      marginTop: 10,
      color: '#555',
      fontSize: 18,
      textAlign: 'center',
    },
    submitButton: {
      backgroundColor: '#007BFF',
      padding: 10,
      borderRadius: 5,
      marginTop: 20,
      alignSelf: 'center',
    },
    photoPreview: {
      width: 100,
      height: 100,
      marginTop: 10,
    },
    // New styles for DisplayAllDetails
  displayContainer: {
    flex: 1,
    padding: 16,
    backgroundColor: '#fff',
    marginBottom: 15,
  },
  displayContent: {
    padding: 16,
  },
  displayHeader: {
    fontSize: 35,
    fontWeight: 'bold',
    marginBottom: 16,
    color: '#333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  displaySection: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderColor: '#ddd',
    paddingBottom: 10,
  },
  displaySectionHeader: {
    fontSize: 30,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  displayTable: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    marginBottom: 16,
    backgroundColor: '#fff',
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  displayRow: {
    flexDirection: 'row',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderColor: '#ddd',
  },
  displayCellHeader: {
    fontWeight: 'bold',
    width: '50%',
    paddingHorizontal: 8,
    fontSize: 19,
  },
  displayCell: {
    width: '50%',
    paddingHorizontal: 8,
    fontSize: 18,
  },
  displayPhotoContainer: {
    marginBottom: 20,
    backgroundColor: '#fff',
    padding: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  displayPhotoText: {
    fontSize: 16,
    marginBottom: 8,
    color: '#555',
  },
  displayPhotoPreview: {
    width: 100,
    height: 100,
    marginTop: 10,
  },
  displayTenantContainer: {
    marginBottom: 20,
    backgroundColor: '#fff',
    padding: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  displayLabel: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#555',
  },
  displayNoDataText: {
    fontSize: 16,
    color: '#999',
    textAlign: 'center',
    marginVertical: 10,
  },
});

export default AppStyles;